name: Procesar Saldos (Gmail & Telegram)

on:
  schedule:
    - cron: '0 09,21 * * *'  # 9:00 AM y 18:00 PM Argentina
  workflow_dispatch:
  repository_dispatch:
    types: [telegram_trigger]

jobs:
  procesar:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar repositorio
      uses: actions/checkout@v3

    - name: Configurar Python con Caché de Dependencias
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'

    - name: Instalar dependencias
      run: |
        python -m pip install --upgrade pip
        pip install requests gspread google-auth google-api-python-client pikepdf pdfplumber

    - name: Ejecutar script de procesamiento
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        SHEET_ID: ${{ secrets.SHEET_ID }}
        GOOGLE_REFRESH_TOKEN: ${{ secrets.GOOGLE_REFRESH_TOKEN }}
        GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
        GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
        FORZAR_EJECUCION: ${{ github.event_name == 'repository_dispatch' && 'true' || 'false' }}
        TELEGRAM_UPDATE_PAYLOAD: ${{ toJson(github.event.client_payload.update) }}
      run: python bot_Saldo.py
